### ISSUE TITLE
How do you obtain the Tidal token needed to use this API?

### ISSUE THREAD

**Issue by jfantell** [lucaslg26/TidalAPI#23]
How do you obtain the Tidal token needed to use this API? Additionally, does this api allow full length playback of songs for an authenticated user?

**Comment by lucaslg26** [comment]
You can get the token sniffing some application that uses TIDAL Playback feature, like CapTune from Sennheiser, the official TIDAL Android app also works. And yes, you get the full lenght .FLAC/ALAC(if you use iOs app token)/AAC, with a valid user.

**Comment by jfantell** [comment]
Thank you so much. I am trying to integrate it into a web app. Full length song playback is supported for the web as well (not just iOS/Android)?

**Comment by lucaslg26** [comment]
It's supported, but the files provided by the web version are encrypted.

**Comment by jonaaa20** [comment]
I've found a Android Token but still doesn't work, i think that the problem is that "X-Tidal-Token" i think you should change to anything else... well, i don't know.

**Comment by lucaslg26** [comment]
I tested yesterday, everything is working fine... Try using the "kgsOOmYk3zShYrNP" token.

**Comment by piotrsmigielski** [comment]
I have found my token in Tidal's cache file in path c:\Users\username\AppData\Roaming\TIDAL\Service Worker\CacheStorage\

**Comment by mikemaccana** [comment]
@piotrsmigielski I'm trying to get this working too -  `.\AppData\Roaming\TIDAL\Service Worker\CacheStorage\` is a folder with subfolders and a lot of different files. What specific file did you find your token in?

**Comment by mikemaccana** [comment]
Nevermind, got it and sent you docs!

**Comment by soufianefariss** [comment]
# Help GUYS!
I can't find Token..
help me out.

**Comment by mikemaccana** [comment]
@soufianefariss Read the new instructions added to the README https://github.com/lucaslg26/TidalAPI -

**Comment by cnucera** [comment]
@mikemaccana I went through the new instructions. I cannot find any request from api.tidal.com (just a few from listen.tidal.com) and therefore couldn't find the token as explained. Any help??

**Comment by ytdlr999** [comment]
@cnucera What client are you using? The browser client uses listen.tidal.com for everything, and you can't use a browser token otherwise tracks will be encrypted.

**Comment by jbschooley** [comment]
@cnucera What client are you using? The browser client uses listen.tidal.com for everything, and you can't use a browser token otherwise tracks will be encrypted.

**Comment by cnucera** [comment]
@jbschooley I am using "TIDAL for Windows", as explained in https://github.com/lucaslg26/TidalAPI. Am I missing something?

**Comment by cnucera** [comment]
managed to get the token, however I get **TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function error**. Anyone still using this successfully?

**Comment by melgu** [comment]
There has to be some way the website and Desktop app calculate or receive the token. Do we know how by now?
I noticed Safari and Firefox on the same machine have the same `x-tidal-token`, so it’s at least unique to the system. So there has to be a unified way to calculate or receive the token based on the machine it’s on. Or is it even unique to an account? I’m unsure because the token even stays the same after I logged out and deleted all cookies and other local storage.

**Comment by melgu** [comment]
I dug into it deeper and found out that all of the potential tokens that the website offers only get you encrypted FLAC files. The decryption key is provided right next to the URL, but I have no idea how to actually decrypt the FLAC files yet.

On the positive side: The respective tokens allow for 1080p video streams. The recommended tokens in this and other threads only get you 720p.

**Comment by matbc92** [comment]
I found in my android phone, in ~/Phone/Android/data/com.aspiro.tidal/cache/okhttp/ there is a bunch of files there the second I oppened ended in ".0" and had the information I needed

**Comment by timotaysci** [comment]
For those having issues getting this and are trying to get tidal working with Strawberry - a very clear guide from ruben2rl can be found in the link below - I will copy here for prosperity:

**https://forum.strawberrymusicplayer.org/topic/23/tidal-account?_=1610739727690&lang=en-GB**



1 - You'll need to install the android app, if you don't have an android phone , maybe you can use an emulator or one of the options for running android apps in a computer.

2 - After you login in the android app, you'll have to navigate to the folder where the app stores the files with the token which are in: /Android/data/com.aspiro.tidal/cache/okhttp (will need to set phone to "File Transfer/Android Auto" in USB preferences in developer options in android) 

Copy all of the files to your computer.

3 - In a Linux terminal, cd to the folder where those files are in your computer and execute this command: grep -r "X-Tidal-Token"
Your token will be revealed

4 - Go to the Tidal settings in Strawberry, check the option 'Use OAuth' and copy the token in the ClientID. Click login and you will be redirected to the browser where you can accept the access to your account and that's it!

**Comment by androidacy-user** [comment]
> For those having issues getting this and are trying to get tidal working with Strawberry - a very clear guide from ruben2rl can be found in the link below - I will copy here for prosperity:
> 
> **https://forum.strawberrymusicplayer.org/topic/23/tidal-account?_=1610739727690&lang=en-GB**
> 
> 1 - You'll need to install the android app, if you don't have an android phone , maybe you can use an emulator or one of the options for running android apps in a computer.
> 
> 2 - After you login in the android app, you'll have to navigate to the folder where the app stores the files with the token which are in: /Android/data/com.aspiro.tidal/cache/okhttp (will need to set phone to "File Transfer/Android Auto" in USB preferences in developer options in android)
> 
> Copy all of the files to your computer.
> 
> 3 - In a Linux terminal, cd to the folder where those files are in your computer and execute this command: grep -r "X-Tidal-Token"
> Your token will be revealed
> 
> 4 - Go to the Tidal settings in Strawberry, check the option 'Use OAuth' and copy the token in the ClientID. Click login and you will be redirected to the browser where you can accept the access to your account and that's it!

THANK YOU!

I was just about to reinstall windows so I could use the tidal app, until i found your answer.

**Comment by userofryzen** [comment]
im trying to figure where is it the "X-Tidal-Token" because it's not in my files... someone can help me? I have access to windows and the android app, but i have tried the android method and it's imposible, simply the X-Tidal-Token appear that way
vary: x-tidal-sessionid,x-tidal-token,authorization

**Comment by fthiery** [comment]
Same here, not working for me. I do find 

> For those having issues getting this and are trying to get tidal working with Strawberry - a very clear guide from ruben2rl can be found in the link below - I will copy here for prosperity:
> 
> **https://forum.strawberrymusicplayer.org/topic/23/tidal-account?_=1610739727690&lang=en-GB**
> 
> 1 - You'll need to install the android app, if you don't have an android phone , maybe you can use an emulator or one of the options for running android apps in a computer.
> 
> 2 - After you login in the android app, you'll have to navigate to the folder where the app stores the files with the token which are in: /Android/data/com.aspiro.tidal/cache/okhttp (will need to set phone to "File Transfer/Android Auto" in USB preferences in developer options in android)
> 
> Copy all of the files to your computer.

Alternatively:
$ adb pull /sdcard/Android/data/com.aspiro.tidal/cache/okhttp

> 3 - In a Linux terminal, cd to the folder where those files are in your computer and execute this command: grep -r "X-Tidal-Token" Your token will be revealed
> 
> 4 - Go to the Tidal settings in Strawberry, check the option 'Use OAuth' and copy the token in the ClientID. Click login and you will be redirected to the browser where you can accept the access to your account and that's it!

I could find `Authorization: Bearer` headers, but that's not working for me (still getting the oops error)

```
$ grep -R Bearer:
bc5bf582b8667f38a16d3e2ec8855837.0:Authorization: Bearer eyJr...OIPg
```

**Comment by Destapler** [comment]
To those who are unable to find their Tidal API token from the android app:
It seems like Tidal for Android has removed the tidal token from the cache files, I use version 2.32.1 which does still save the token to the cache files, and this token works to authorize Strawberry for me.

**Comment by Xunjin** [comment]
Can confirm @Destapler info, in the recent versions in android app there is no token in cache files, does anyone have another solution?

**Comment by thecountrox** [comment]
> Can confirm @Destapler info, in the recent versions in android app there is no token in cache files, does anyone have another solution?

old version actually still works :D , i just got mine working rn

**Comment by E34rrsff** [comment]
You can install the older version from Aptoide and then the files will appear
https://en.aptoide.com

**Comment by BlueManCZ** [comment]
I can confirm that you can still get a working `X-Tidal-Token` from version [2.32.1](https://mobile.softpedia.com/apk/tidal/2.32.1/) of the TIDAL APK. :tada: 

Some users [reported](https://forum.strawberrymusicplayer.org/post/1530) that it was probably renamed to `x-tidal-token` in newer versions, but I had no luck with that.

**Comment by jisa8438** [comment]
> It seems like Tidal for Android has removed the tidal token from the cache files, I us

Does this token can just keep for 24 hours?

**Comment by ValeZAA** [comment]
> I can confirm that you can still get a working `X-Tidal-Token` from version [2.32.1](https://mobile.softpedia.com/apk/tidal/2.32.1/) of the TIDAL APK. 🎉
> 
> Some users [reported](https://forum.strawberrymusicplayer.org/post/1530) that it was probably renamed to `x-tidal-token` in newer versions, but I had no luck with that.

You cannot log in with such an old version anymore. Windows x-tidal-token does not work either, Bearer token it is not even pure base64 on Windows.
