### ISSUE TITLE
Master quality

### ISSUE THREAD

**Issue by silvertriclops** [lucaslg26/TidalAPI#25]
Is there a way to get Master quality yet?

I wrote an app about a year and a half ago to download and tag music from Tidal and I'm surprised its still running...but it doesn't get MQA. Not necessary but it would be cool for future proofing. So far the only way I can find to stream MQA is through the desktop app which encrypts files. Android and iOS tokens with the same get request only return the normal FLAC quality.

I'm under the impression that some of the devices that support Tidal support MQA and it might be possible to get a token from one of them. Is there any way to do that besides buying the device? Or if anyone has such a device could they get the token?

**Comment by lucaslg26** [comment]
I wrote an app two years ago and it's running flawlessy too, haha.
Yes, It's possible to get the MQA quality, you just need a enabled device token. 
It's easy to find, let's check the source of the TIDAL Kodi Plugin ;)

**Comment by silvertriclops** [comment]
Thanks! Exactly what I needed.

[For anyone else wondering](https://github.com/arnesongit/plugin.audio.tidal2/blob/master/resources/lib/koditidal.py#L730)
