### ISSUE TITLE
deasync issue

### ISSUE THREAD

**Issue by gyurobenjamin** [lucaslg26/TidalAPI#27]
/data//tidal/node_modules/bindings/bindings.js:91
throw err
^
Error: Could not locate the bindings file. Tried:
→ /data//tidal/node_modules/deasync/build/deasync.node
→ /data//tidal/node_modules/deasync/build/Debug/deasync.node
→ /data//tidal/node_modules/deasync/build/Release/deasync.node
→ /data//tidal/node_modules/deasync/out/Debug/deasync.node
→ /data//tidal/node_modules/deasync/Debug/deasync.node
→ /data//tidal/node_modules/deasync/out/Release/deasync.node
→ /data//tidal/node_modules/deasync/Release/deasync.node
→ /data//tidal/node_modules/deasync/build/default/deasync.node
→ /data//tidal/node_modules/deasync/compiled/6.11.0/linux/arm/deasync.node
at bindings (/data//tidal/node_modules/bindings/bindings.js:88:9)
at /data//tidal/node_modules/deasync/index.js:34:32
at Object.<anonymous> (/data//tidal/node_modules/deasync/index.js:76:2)

**Comment by lucaslg26** [comment]
Solved.
